# Step 1: Build the React application
FROM node:18 AS build

WORKDIR /app

COPY ./client/package.json ./client/package-lock.json ./
RUN npm install

COPY ./client ./
RUN npm run build

# Step 2: Serve the React application using Nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
